### ISSUE TITLE
single core case (concerning pull request #24)

### ISSUE THREAD

**Issue by drazioti** [drazioti/Carmichael#25]
[single core case] #24 
```
./a.out 5 1 1 1 1 1 --ham 15 -b 20 -f 1
Lambda is : 99984595647159336960000
hamming   : 15
P size is : 1612
looking for Carmichaels with 1597 factors
density of the problem     : 21.743430
Size of I is : 32
h1 = 7
h2 = 8
frag = 1
The first set U1, has been stored in memory
Hashtable size : 3365856
```
Although the right value for lambda is 480480 and for the P size, 61.

**Comment by etiganou** [comment]
κάτι βάζετε λάθος το single core τρέχει σωστά, εγω για το ίδιο παράδειγμα έχω P size 61 και L = 480480

**Comment by drazioti** [comment]
I used the last pull request (24). If you change anything you have to push and then pull again.

**Comment by etiganou** [comment]
Check your inputs in carmi.cpp. You have to hardcode values for H[], r

**Comment by etiganou** [comment]
I used this code and it works fine

**Comment by drazioti** [comment]
OK. Right. My bad. I forgot that we do not have args in single core.
