### ISSUE TITLE
Generating random seed

### ISSUE THREAD

**Issue by etiganou** [drazioti/Carmichael#28]

**Comment by etiganou** [comment]
Τότε που κοιτούσαμε το θέμα της random είχαμε χρησιμοποιήσει την Mersenne Twister της GMP και σκεφτήκαμε ότι θα είναι trully random. Τα test που κάναμε τότε ήταν επειδή στο πρόγραμμα το gen_I γίνεται με 2 τρόπους ανάλογα με το μέγεθος του P_set και ο πρώτος δίνει trully random αλλά της gmp δεν είναι τελικά random. Κάθε φορα που τρέχουμε το πρόγραμμα τα I είναι διαφορετικά σε κάθε γύρω αλλά τα ίδια για κάθε διαφορετική εκτέλεση του προγράμματος

**Comment by drazioti** [comment]
#27  the same, whenever I run the code for ./a.out 10 4 3 3 1 1 --ham 11 -b 26 -f 1 always the 8th round will find the solution.

**Comment by etiganou** [comment]
Thats because every time the program runs from the beginnnig the same sequence of I1, I2 indexes will appear... gmp_rand_state is not truly random

**Comment by etiganou** [comment]
I am searching for a way to create rael time random seed

**Comment by drazioti** [comment]
there is not something like truly random. To get entropy you can use the urandom of the system. I thought that was something resolved, months ago.

**Comment by etiganou** [comment]
ναι και γω έτσι πίστευα αλλά η random της gmp δεν δουλεύει όπως λέει

**Comment by drazioti** [comment]
One other things that needs care is not to store {01,...,n}, you have to do rejection sample, as the paper describes. I am sure that is not a mistake of gmp..maybe a wrong use of gmp
