### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by drazioti** [drazioti/Carmichael#31]
Στον αλλον υπολογιστη εχω το εξης

$g++ --std=c++11 carmi.cpp Combinations.cpp -lgmpxx -lgmp -lcrypto -fopenmp

g++ --std=c++11 carmi.cpp Combinations.cpp -lgmpxx -lgmp -lcrypto -fopenmp
/tmp/ccKrur6S.o: In function `divisors(int*, int*, int, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, unsigned char**&)':
carmi.cpp:(.text+0x46b): undefined reference to `mpz_2_ull(__gmp_expr<__mpz_struct [1], __mpz_struct [1]>)'
carmi.cpp:(.text+0x6b7): undefined reference to `arrcpy(__gmp_expr<__mpz_struct [1], __mpz_struct [1]>*&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>*&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&)'
/tmp/ccKrur6S.o: In function `make_P_set(int*, int*, int, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, std::list<unsigned char*, std::allocator<unsigned char*> >&)':
carmi.cpp:(.text+0xb26): undefined reference to `mpz_2_ull(__gmp_expr<__mpz_struct [1], __mpz_struct [1]>)'
/tmp/ccKrur6S.o: In function `T_set(int*, int, unsigned char**&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>**&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, int, double, int, char)':
carmi.cpp:(.text+0xf55): undefined reference to `get_P_element(int*&, unsigned char*&, int)'
carmi.cpp:(.text+0x1088): undefined reference to `product_attack_1(int*&, int, unsigned char**&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>**&, int, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, std::list<int*, std::allocator<int*> >&, std::list<int*, std::allocator<int*> >&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, double, int, char)'
/tmp/ccKrur6S.o: In function `extract_number(__gmp_expr<__mpz_struct [1], __mpz_struct [1]>*&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>**&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, std::list<int*, std::allocator<int*> >&, std::list<int*, std::allocator<int*> >&, int, int, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>*&)':
carmi.cpp:(.text+0x1844): undefined reference to `is_carmichael(__gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>*&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&)'
/tmp/ccKrur6S.o: In function `main':
carmi.cpp:(.text+0x2ff3): undefined reference to `randomize_I(gmp_randclass&, unsigned int)'
carmi.cpp:(.text+0x3152): undefined reference to `gen_I(__gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>&, int, __gmp_expr<__mpz_struct [1], __mpz_struct [1]>**&, gmp_randclass&, unsigned int)'
collect2: error: ld returned 1 exit status

Φυσικα αποτυγχανει και η make.
Eχει  καταφερει να δημιουργησει τα object files.
Το Makefile δε νομιζω να εχει θέμα. Ίσως τα header files

**Comment by vamartid** [comment]
what is the output of "g++ --version" ?

**Comment by drazioti** [comment]
Πριν ηταν OK, δεν βλεπω το λογο τωρα να μην ειναι. 

```
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.9.2-10ubuntu13' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Ubuntu 4.9.2-10ubuntu13) 
```

**Comment by etiganou** [comment]
Δοκιμάστε αυτό: " g++ --std=c++11 carmi.cpp Combinations.cpp subset_produt.cpp  -lgmpxx -lgmp -lcrypto -fopenmp "

**Comment by drazioti** [comment]
solved in #33

**Comment by etiganou** [comment]
There is still a problem ?

**Comment by drazioti** [comment]
κανει compile κανονικα η make αλλά όταν τρεχω το παράλληλο, δειχνει η htop να τρεχει σε ενα πυρηνα

**Comment by vamartid** [comment]
I placed  $(ALL_LIBS) after each g++ call

**Comment by vamartid** [comment]
is this ok in both versions of g++?

**Comment by drazioti** [comment]
nai nomizw einai ok twra
